name: "CI"

on:
  pull_request:
  push:
    branches:
      - master

env:
  COMPOSER_ROOT_VERSION: "1.99.99"

jobs:
  coverage:
    name: "Coverage"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "latest"
          coverage: "pcov"
          ini-values: "memory_limit=-1, zend.assertions=1, error_reporting=-1, display_errors=On"
          tools: "composer"
      - name: "Prepare for tests"
        run: "mkdir -p build/logs"
      - uses: "ramsey/composer-install@v2"
      - name: "Run unit tests"
        run: "./vendor/bin/phpunit --colors=always --coverage-clover build/logs/clover.xml --coverage-text"
      - name: "Publish coverage report to Codecov"
        uses: "codecov/codecov-action@v2"

  unit-tests:
    name: "Unit Tests"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        php-version: [ "8.0", "8.1" ]
    steps:
      - uses: "actions/checkout@v2"
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "none"
          ini-values: "memory_limit=-1, zend.assertions=1, error_reporting=-1, display_errors=On"
          tools: "composer"
      - name: "Prepare for tests"
        run: "mkdir -p build/logs"
      - uses: "ramsey/composer-install@v2"
      - name: "Run unit tests"
        run: "./vendor/bin/phpunit --colors=always"